# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-14 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='')),
                ('decsription', models.CharField(max_length=500)),
            ],
        ),
    ]
